[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "deps_installer"
version = "0.1.0"
description = "A minimal Python project example."
requires-python = ">=3.8"
dependencies = [
    "pyuac>=0.0.3",
    "pywin32>=311"
]