
name: Build and Release

on:
    push:
        tags:
            - "*"

jobs:
    builder:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt update && sudo apt upgrade -y
            - run: sudo apt install -y python3 python3-pip sed
            - run: pip3 install -r requirements.txt
            - name: Set version in pyproject.toml
              run: sed -i "s/{{ VERSION }}/${{ github.ref_name }}/g" pyproject.toml
            - run: python -m build
            # - run: mkdir artifacts
            # - run: cp dist/* artifacts
            - name: Publish package to PyPi
              uses: pypa/gh-action-pypi-publish@release/v1
            # - name: Upload Build Artifact
            #   uses: actions/upload-artifact@v4
            #   with:
            #       name: build
            #       path: artifacts
            #       retention-days: 5